// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List the signed-in user's BidBox projects with bid due dates and status.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25)."),
    status: z.enum(["live", "dead", "all"]).optional().describe("Filter by status (default all).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = sb(ctx).from("projects").select("id,name,location,agency,bid_due_at,status,created_at").order("bid_due_at", { ascending: true, nullsFirst: false }).limit(limit ?? 25);
    if (status && status !== "all") query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch a single BidBox project with its files and bid submissions.",
  inputSchema: {
    project_id: z2.string().uuid().describe("Project UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = sb2(ctx);
    const [{ data: project, error: pErr }, { data: files }, { data: bids }] = await Promise.all([
      client.from("projects").select("*").eq("id", project_id).maybeSingle(),
      client.from("project_files").select("id,file_name,file_url,created_at").eq("project_id", project_id),
      client.from("bids").select("id,submitted_at,bidder_name,company_name,email,division,file_url").eq("project_id", project_id)
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (!project) return { content: [{ type: "text", text: "Project not found or not accessible" }], isError: true };
    const payload = { project, files: files ?? [], bids: bids ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-opportunities.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_opportunities_default = defineTool3({
  name: "list_opportunities",
  title: "List opportunities",
  description: "List public-works bid opportunities discovered by BidBox, filterable by county and search term.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 25)."),
    county: z3.string().optional().describe("Filter by county name, e.g. 'Los Angeles'."),
    search: z3.string().optional().describe("Free-text match against title/agency.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, county, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb3(ctx).from("opportunities").select("id,title,agency,county,bid_due_at,estimated_value,source_url,status").order("bid_due_at", { ascending: true, nullsFirst: false }).limit(limit ?? 25);
    if (county) q = q.eq("county", county);
    if (search) q = q.or(`title.ilike.%${search}%,agency.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { opportunities: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ztuyjlyuzasbceepezua";
var mcp_default = defineMcp({
  name: "bidbox-mcp",
  title: "BidBox",
  version: "0.1.0",
  instructions: "Tools for BidBox \u2014 the bid room for general contractors. Use `list_projects` and `get_project` to inspect the signed-in user's bid projects, files, and subcontractor bid submissions. Use `list_opportunities` to browse discovered public-works bid opportunities.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, get_project_default, list_opportunities_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
