-- Portal Intelligence summary columns on opportunity_candidates.
--
-- portal_summary:    plain-text executive summary generated from portal
--                    metadata only (no document download required).
--                    Generated by the portal_intelligence worker task,
--                    which runs after bid_item_scan completes.
--
-- portal_summary_at: when the summary was last generated. Used by the
--                    UI to decide whether to show the portal summary
--                    or the richer F4 intelligence summary.
--
-- These are OML-layer columns. F4 (project intelligence) generates
-- its own richer report in opportunity_intelligence_reports.
-- The UI should prefer F4 when available; fall back to portal_summary.

ALTER TABLE public.opportunity_candidates
  ADD COLUMN IF NOT EXISTS portal_summary    text,
  ADD COLUMN IF NOT EXISTS portal_summary_at timestamptz;
