INSERT INTO opportunity_sources (name, portal_type, listing_url, scan_enabled, scan_interval_hours)
VALUES
  ('City of Beverly Hills', 'planetbids', 'https://vendors.planetbids.com/portal/39493/bo/bo-search', true, 24),
  ('City of Burbank', 'planetbids', 'https://vendors.planetbids.com/portal/14210/bo/bo-search', true, 24),
  ('Burbank-Glendale-Pasadena Airport Authority', 'planetbids', 'https://vendors.planetbids.com/portal/21910/bo/bo-search', true, 24),
  ('City of Carlsbad', 'planetbids', 'https://vendors.planetbids.com/portal/27970/bo/bo-search', true, 24),
  ('City of Chula Vista', 'planetbids', 'https://vendors.planetbids.com/portal/15381/bo/bo-search', true, 24),
  ('City of Corona', 'planetbids', 'https://vendors.planetbids.com/portal/39497/bo/bo-search', true, 24),
  ('City of Costa Mesa', 'planetbids', 'https://vendors.planetbids.com/portal/45476/bo/bo-search', true, 24),
  ('City of Culver City', 'planetbids', 'https://vendors.planetbids.com/portal/39483/bo/bo-search', true, 24),
  ('City of Diamond Bar', 'planetbids', 'https://vendors.planetbids.com/portal/39500/bo/bo-search', true, 24),
  ('City of Duarte', 'planetbids', 'https://vendors.planetbids.com/portal/42035/bo/bo-search', true, 24),
  ('City of Glendale', 'planetbids', 'https://vendors.planetbids.com/portal/39503/bo/bo-search', true, 24),
  ('City of Huntington Beach', 'planetbids', 'https://vendors.planetbids.com/portal/15340/bo/bo-search', true, 24),
  ('City of Inglewood', 'planetbids', 'https://vendors.planetbids.com/portal/45619/bo/bo-search', true, 24),
  ('City of Irvine', 'planetbids', 'https://vendors.planetbids.com/portal/15927/bo/bo-search', true, 24),
  ('City of Jurupa Valley', 'planetbids', 'https://vendors.planetbids.com/portal/26879/bo/bo-search', true, 24),
  ('City of La Canada Flintridge', 'planetbids', 'https://vendors.planetbids.com/portal/62508/bo/bo-search', true, 24),
  ('City of Long Beach', 'planetbids', 'https://vendors.planetbids.com/portal/15810/bo/bo-search', true, 24),
  ('Long Beach Unified School District', 'planetbids', 'https://vendors.planetbids.com/portal/23758/bo/bo-search', true, 24),
  ('City of Los Angeles', 'planetbids', 'https://vendors.planetbids.com/portal/23749/bo/bo-search', true, 24),
  ('Los Angeles Community College District', 'planetbids', 'https://vendors.planetbids.com/portal/21372/bo/bo-search', true, 24),
  ('Los Angeles County Office of Education', 'planetbids', 'https://vendors.planetbids.com/portal/61954/bo/bo-search', true, 24),
  ('Los Angeles World Airports', 'planetbids', 'https://vendors.planetbids.com/portal/48397/bo/bo-search', true, 24),
  ('Metropolitan Water District of Southern California', 'planetbids', 'https://vendors.planetbids.com/portal/16151/bo/bo-search', true, 24),
  ('Moreno Valley Unified School District', 'planetbids', 'https://vendors.planetbids.com/portal/59999/bo/bo-search', true, 24),
  ('City of Murrieta', 'planetbids', 'https://vendors.planetbids.com/portal/17992/bo/bo-search', true, 24),
  ('City of National City', 'planetbids', 'https://vendors.planetbids.com/portal/24103/bo/bo-search', true, 24),
  ('City of Newport Beach', 'planetbids', 'https://vendors.planetbids.com/portal/22078/bo/bo-search', true, 24),
  ('Newport-Mesa Unified School District', 'planetbids', 'https://vendors.planetbids.com/portal/46422/bo/bo-search', true, 24),
  ('City of Norwalk', 'planetbids', 'https://vendors.planetbids.com/portal/54783/bo/bo-search', true, 24),
  ('Omnitrans', 'planetbids', 'https://vendors.planetbids.com/portal/18046/bo/bo-search', true, 24),
  ('City of Ontario', 'planetbids', 'https://vendors.planetbids.com/portal/11434/bo/bo-search', true, 24),
  ('Orange County Fire Authority', 'planetbids', 'https://vendors.planetbids.com/portal/14773/bo/bo-search', true, 24),
  ('Orange County Sanitation District', 'planetbids', 'https://vendors.planetbids.com/portal/14058/bo/bo-search', true, 24),
  ('Orange Unified School District', 'planetbids', 'https://vendors.planetbids.com/portal/15578/bo/bo-search', true, 24),
  ('City of Palm Springs', 'planetbids', 'https://vendors.planetbids.com/portal/47688/bo/bo-search', true, 24),
  ('City of Pomona', 'planetbids', 'https://vendors.planetbids.com/portal/24662/bo/bo-search', true, 24),
  ('Port of Long Beach', 'planetbids', 'https://vendors.planetbids.com/portal/19236/bo/bo-search', true, 24),
  ('Port of Los Angeles', 'planetbids', 'https://vendors.planetbids.com/portal/42217/bo/bo-search', true, 24),
  ('City of Redlands', 'planetbids', 'https://vendors.planetbids.com/portal/24639/bo/bo-search', true, 24),
  ('City of Riverside', 'planetbids', 'https://vendors.planetbids.com/portal/39475/bo/bo-search', true, 24),
  ('San Diego County Regional Airport Authority', 'planetbids', 'https://vendors.planetbids.com/portal/16725/bo/bo-search', true, 24),
  ('City of San Diego', 'planetbids', 'https://vendors.planetbids.com/portal/17950/bo/bo-search', true, 24),
  ('San Diego Unified School District', 'planetbids', 'https://vendors.planetbids.com/portal/43764/bo/bo-search', true, 24),
  ('City of Santa Ana', 'planetbids', 'https://vendors.planetbids.com/portal/20137/bo/bo-search', true, 24),
  ('Santa Clarita Community College District', 'planetbids', 'https://vendors.planetbids.com/portal/53162/bo/bo-search', true, 24),
  ('Santa Clarita Valley Water Agency', 'planetbids', 'https://vendors.planetbids.com/portal/27355/bo/bo-search', true, 24),
  ('City of Seal Beach', 'planetbids', 'https://vendors.planetbids.com/portal/39491/bo/bo-search', true, 24),
  ('City of Temecula', 'planetbids', 'https://vendors.planetbids.com/portal/14837/bo/bo-search', true, 24),
  ('City of Torrance', 'planetbids', 'https://vendors.planetbids.com/portal/47426/bo/bo-search', true, 24),
  ('Transportation Corridor Agencies', 'planetbids', 'https://vendors.planetbids.com/portal/24054/bo/bo-search', true, 24),
  ('Val Verde Unified School District', 'planetbids', 'https://vendors.planetbids.com/portal/70300/bo/bo-search', true, 24),
  ('City of West Hollywood', 'planetbids', 'https://vendors.planetbids.com/portal/22761/bo/bo-search', true, 24),
  ('City of Westlake Village', 'planetbids', 'https://vendors.planetbids.com/portal/59523/bo/bo-search', true, 24),
  ('City of Wildomar', 'planetbids', 'https://vendors.planetbids.com/portal/66534/bo/bo-search', true, 24)
ON CONFLICT (listing_url) DO UPDATE
SET
  name = EXCLUDED.name,
  portal_type = EXCLUDED.portal_type,
  scan_enabled = EXCLUDED.scan_enabled,
  scan_interval_hours = EXCLUDED.scan_interval_hours,
  updated_at = now();